version: '3.5'

services:
  php:
    build: .
    volumes:
      - .:/app
    network_mode: host

  php8:
    build:
      context: .
      dockerfile: Dockerfile.php8
    volumes:
      - .:/app
    network_mode: host
